#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" |  sudo tee /var/www/html/index.html

sed -i '/^\s*location \/ {/,/^\s*}$/c
location \/redirect_me {
    return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
}' /etc/nginx/sites-available/default


sudo service nginx restart
