#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header

sudo apt update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# create a custom 404.html page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# configure the sever block
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        # Add a custom header
        add_header X-Served-By $HOSTNAME;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
                internal;
        }

}" > /etc/nginx/sites-available/default

sudo service nginx restart
