#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

apt-get update
apt-get -y install haproxy

echo "frontend http
        bind *:80
        mode http
        use_backend web-backend

backend web-backend
        balance roundrobin
        option forwardfor
        server 435611-web-01 34.207.63.157:80 check
        server 435611-web-02 54.85.3.206:80 check
        " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
