#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

file=~/new_hosts

echo "127.0.0.2 localhost" > $file

echo "8.8.8.8 facebook.com" >> $file

cp -f $file /etc/hosts
