#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# ip -4 address show | grep inet | cut -d " " -f 6 | cut -d "/" -f 1

ifconfig | grep -w "inet" | cut -d " " -f 10
