#!/usr/bin/env bash
# configure the container to run nginx under nginx user on port 8080
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx
chmod 755 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
